name: 'Auto Stats'
description: 'Auto Stats Action enables to generate a repository statistics like total number of file, number of words in every file, etc.'

branding:
  icon: database
  color: gray-dark

inputs:
  name: 
    description: 'Username for Git'
    required: false
  email: 
    description: 'Email for Git'
    required: false
  branch:
    description: 'Branch to Push Changes.'
    required: true
  committer: 
    description: 'Commiter Name and Email'
    required: false
  commit-message: 
    description: 'Commit Message'
    required: false
  github-token:
    description: 'Github token for Authorization'
    required: true

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        NAME: ${{ github.repository_owner }}
        EMAIL: ${{ github.repository_owner_email }}
        COMMITTER: ${{ inputs.committer }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        COMMIT-MESSAGE: ${{ inputs.commit-message }}