name: 'Auto Stats'
description: 'Auto Stats Action enables generation of repository statistics like total number of files, number of words in every file, etc.'

branding:
  icon: database
  color: gray-dark

inputs:
  name: 
    description: 'Username for Git'
    required: false
    default: 'github-actions[bot]'
  email: 
    description: 'Email for Git'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'
  message: 
    description: 'Commit Message'
    required: false
    default: 'Updated Repo Stats'
  github-token:
    description: 'GitHub token for Authorization'
    required: true
  branch:
    description: 'Branch to Push Changes'
    required: false
    default: 'master'
  options:
    description: 'Commit flags'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - run: ./entrypoint.sh
      shell: bash
      env:
        NAME: ${{ inputs.name }}
        EMAIL: ${{ inputs.email }}
        COMMITTER: ${{ inputs.committer || inputs.name }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        COMMIT_MESSAGE: ${{ inputs.message }}