name: CI / Deploy to GHCR

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  call-ghcr-workflow:
    uses: offensive-vk/Assets/.github/workflows/ghcr.yml@master
    with:
      author: "Vedansh"
      title: "auto-stats"
      description: "Generate a repository statistics file like total number of file, number of words in every file, etc."
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}