name: CI / Test Action

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  stats:
    name: Generate Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Stats
        uses: ./
        with:
          branch: ${{ github.ref_name || 'master' }}
          github-token: ${{ secrets.BOT_TOKEN || secrets.GITHUB_TOKEN }}
          message: 'Updated Daily Statistics.'
