name: CI / Test Action

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"] 
  workflow_dispatch:

jobs:
   stats:
    name: Generate Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Stats
        uses: ./
        with:
            branch: ${{ github.head_ref || 'master' }}
            github-token: ${{ secrets.BOT_TOKEN || secrets.GITHUB_TOKEN }}
            message: 'Updated Daily Statistics.'