name: CI / Test

on: 
  push: 
    branches: ["**"]

jobs:
   stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Change Permissions
        run: chmod +x entrypoint.sh

      - name: Generate Stats
        uses: ./
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: Updated Daily Statistics.
            committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
